version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diegodb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
