services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:diegodb@db:5432/Api_db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diegodb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
